import {
  ArrowRightIcon,
  ArrowLeftIcon,
  TargetIcon,
  BlueprintIcon,
  ScrewdriverIcon,
  ShieldCheckIcon,
  CloudRainIcon,
  WrenchIcon,
  FrameCornersIcon,
  HouseSimpleIcon,
  BuildingsIcon,
  BuildingOfficeIcon,
  FactoryIcon,
  EqualsIcon,
  XIcon,
} from "@phosphor-icons/react";

export const Icons = {
  arrowRight: ArrowRightIcon,
  arrowLeft: ArrowLeftIcon,
  target: TargetIcon,
  blueprint: BlueprintIcon,
  screwdriver: ScrewdriverIcon,
  shieldCheck: ShieldCheckIcon,
  cloudRain: CloudRainIcon,
  wrench: WrenchIcon,
  frameCorners: FrameCornersIcon,
  houseSimple: HouseSimpleIcon,
  buildings: BuildingsIcon,
  buildingOffice: BuildingOfficeIcon,
  factory: FactoryIcon,
  equals: EqualsIcon,
  x: XIcon,
};
